# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5efb3eece80fda172fa3c5fe6aa70360ba456986e43751294327d0bdf59cca2a8f15ee85e49e203308c8838926fc9f5d0b3aefa0ec64aeba391eb0e79e1c686f

test:
  secret_key_base: 36742dcf54a2a4cfa46a5ce5e9b9e7ccf2b74c66383a035ab539b87dcbec34f4d27a276de5859e9f7138b051580ae2cf6ccc1e3ece6354e40ddb63593464221a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
