# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Team.create(name:'Arizona Cardinals',abbreviation:'ARI',conference:'NFC',division:'West',location:'Arizona')
Team.create(name:'Atlanta Falcons',abbreviation:'ATL',conference:'NFC',division:'South',location:'Atlanta')
Team.create(name:'Baltimore Ravens',abbreviation:'BAL',conference:'AFC',division:'North',location:'Baltimore')
Team.create(name:'Buffalo Bills',abbreviation:'BUF',conference:'AFC',division:'East',location:'Buffalo')
Team.create(name:'Carolina Panthers',abbreviation:'CAR',conference:'NFC',division:'South',location:'Carolina')
Team.create(name:'Chicago Bears',abbreviation:'CHI',conference:'NFC',division:'North',location:'Chicago')
Team.create(name:'Cincinnati Bengals',abbreviation:'CIN',conference:'AFC',division:'North',location:'Cincinnati')
Team.create(name:'Cleveland Browns',abbreviation:'CLE',conference:'AFC',division:'North',location:'Cleveland')
Team.create(name:'Dallas Cowboys',abbreviation:'DAL',conference:'NFC',division:'East',location:'Dallas')
Team.create(name:'Denver Broncos',abbreviation:'DEN',conference:'AFC',division:'West',location:'Denver')
Team.create(name:'Detroit Lions',abbreviation:'DET',conference:'NFC',division:'North',location:'Detroit')
Team.create(name:'Green Bay Packers',abbreviation:'GB',conference:'NFC',division:'North',location:'Green Bay')
Team.create(name:'Houston Texans',abbreviation:'HOU',conference:'AFC',division:'South',location:'Houston')
Team.create(name:'Indianapolis Colts',abbreviation:'IND',conference:'AFC',division:'South',location:'Indianapolis')
Team.create(name:'Jacksonville Jaguars',abbreviation:'JAX',conference:'AFC',division:'South',location:'Jacksonville')
Team.create(name:'Kansas City Chiefs',abbreviation:'KC',conference:'AFC',division:'West',location:'Kansas City')
Team.create(name:'Miami Dolphins',abbreviation:'MIA',conference:'AFC',division:'East',location:'Miami')
Team.create(name:'Minnesota Vikings',abbreviation:'MIN',conference:'NFC',division:'North',location:'Minnesota')
Team.create(name:'New England Patriots',abbreviation:'NE',conference:'AFC',division:'East',location:'New England')
Team.create(name:'New Orleans Saints',abbreviation:'NO',conference:'NFC',division:'South',location:'New Orleans')
Team.create(name:'NY Giants',abbreviation:'NYG',conference:'NFC',division:'East',location:'NY')
Team.create(name:'NY Jets',abbreviation:'NYJ',conference:'AFC',division:'East',location:'NY')
Team.create(name:'Oakland Raiders',abbreviation:'OAK',conference:'AFC',division:'West',location:'Oakland')
Team.create(name:'Philadelphia Eagles',abbreviation:'PHI',conference:'NFC',division:'East',location:'Philadelphia')
Team.create(name:'Pittsburgh Steelers',abbreviation:'PIT',conference:'AFC',division:'North',location:'Pittsburgh')
Team.create(name:'Los Angeles Chargers',abbreviation:'LAC',conference:'AFC',division:'West',location:'Los Angeles')
Team.create(name:'San Francisco 49ers',abbreviation:'SF',conference:'NFC',division:'West',location:'San Francisco')
Team.create(name:'Seattle Seahawks',abbreviation:'SEA',conference:'NFC',division:'West',location:'Seattle')
Team.create(name:'Los Angeles Rams',abbreviation:'LA',conference:'NFC',division:'West',location:'Los Angeles')
Team.create(name:'Tampa Bay Buccaneers',abbreviation:'TB',conference:'NFC',division:'South',location:'Tampa Bay')
Team.create(name:'Tennessee Titans',abbreviation:'TEN',conference:'AFC',division:'South',location:'Tennessee')
Team.create(name:'Washington Redskins',abbreviation:'WAS',conference:'NFC',division:'East',location:'Washington')
